//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoktorKapisi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorGiris
    {
        public int id { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string UzmanlikAlani { get; set; }
        public string Telefon { get; set; }
        public string Sehir { get; set; }
        public byte[] KimlikBelgesi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> SehirId { get; set; }
        public Nullable<int> CinsiyetId { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual Cinsiyet Cinsiyet1 { get; set; }
    }
}
